---
version: "3.8"
name: indoorrouter
services:
  db:
    build:
      context: .
      dockerfile: ./dockerfiles/postgis.Dockerfile
    image: "gitlab.fit.cvut.cz:5000/richtm12/bp-code/postgis"
    environment:
      POSTGRES_USER: indoorrouter
      POSTGRES_PASSWORD: indoorrouter
      POSTGRES_DATABASE: indoorrouter
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 5
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: indoorrouter@example.org
      PGADMIN_DEFAULT_PASSWORD: indoorrouter
    ports:
      - "127.0.0.1:8000:80"
    depends_on:
      db:
        condition: service_healthy
  import:
    environment:
      PGHOST: db
      PGUSER: indoorrouter
      PGPASSWORD: indoorrouter
      PGDATABASE: indoorrouter
      EXTRACT_URL: https://download.geofabrik.de/europe/czech-republic-latest.osm.pbf
      UPDATE_SERVER_URL: https://planet.openstreetmap.org/replication/minute/
      BBOX: 14.384794,50.099895,14.396553,50.106529
    volumes:
      - "./import-data:/app/data"
      - "./import:/app/import"
    build:
      context: .
      dockerfile: ./dockerfiles/osm2pgsql.Dockerfile
    depends_on:
      db:
        condition: service_healthy


volumes:
  db_data:
    driver: local
