/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type { RoutingConfig } from '../models';
import { RoutingConfigFromJSON, RoutingConfigToJSON } from '../models';

/**
 *
 */
export class ConfigApi extends runtime.BaseAPI {
	/**
	 */
	async configGetRaw(
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<RoutingConfig>> {
		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		const response = await this.request(
			{
				path: `/config`,
				method: 'GET',
				headers: headerParameters,
				query: queryParameters
			},
			initOverrides
		);

		return new runtime.JSONApiResponse(response, (jsonValue) => RoutingConfigFromJSON(jsonValue));
	}

	/**
	 */
	async configGet(
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<RoutingConfig> {
		const response = await this.configGetRaw(initOverrides);
		return await response.value();
	}
}
