/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  RoutingResult,
} from '../models';
import {
    RoutingResultFromJSON,
    RoutingResultToJSON,
} from '../models';

export interface RouteGetRequest {
    from?: string;
    to?: string;
}

/**
 * 
 */
export class RoutingApi extends runtime.BaseAPI {

    /**
     */
    async routeGetRaw(requestParameters: RouteGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RoutingResult>> {
        const queryParameters: any = {};

        if (requestParameters.from !== undefined) {
            queryParameters['from'] = requestParameters.from;
        }

        if (requestParameters.to !== undefined) {
            queryParameters['to'] = requestParameters.to;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/route`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RoutingResultFromJSON(jsonValue));
    }

    /**
     */
    async routeGet(requestParameters: RouteGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RoutingResult> {
        const response = await this.routeGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
