/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BboxSouthWest
 */
export interface BboxSouthWest {
    /**
     * 
     * @type {number}
     * @memberof BboxSouthWest
     */
    longitude: number;
    /**
     * 
     * @type {number}
     * @memberof BboxSouthWest
     */
    latitude: number;
}

/**
 * Check if a given object implements the BboxSouthWest interface.
 */
export function instanceOfBboxSouthWest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "longitude" in value;
    isInstance = isInstance && "latitude" in value;

    return isInstance;
}

export function BboxSouthWestFromJSON(json: any): BboxSouthWest {
    return BboxSouthWestFromJSONTyped(json, false);
}

export function BboxSouthWestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BboxSouthWest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'longitude': json['longitude'],
        'latitude': json['latitude'],
    };
}

export function BboxSouthWestToJSON(value?: BboxSouthWest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'longitude': value.longitude,
        'latitude': value.latitude,
    };
}

