/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BboxSouthWest } from './BboxSouthWest';
import {
	BboxSouthWestFromJSON,
	BboxSouthWestFromJSONTyped,
	BboxSouthWestToJSON
} from './BboxSouthWest';

/**
 *
 * @export
 * @interface Bbox
 */
export interface Bbox {
	/**
	 *
	 * @type {BboxSouthWest}
	 * @memberof Bbox
	 */
	southWest: BboxSouthWest;
	/**
	 *
	 * @type {BboxSouthWest}
	 * @memberof Bbox
	 */
	northEast: BboxSouthWest;
}

/**
 * Check if a given object implements the Bbox interface.
 */
export function instanceOfBbox(value: object): boolean {
	let isInstance = true;
	isInstance = isInstance && 'southWest' in value;
	isInstance = isInstance && 'northEast' in value;

	return isInstance;
}

export function BboxFromJSON(json: any): Bbox {
	return BboxFromJSONTyped(json, false);
}

export function BboxFromJSONTyped(json: any, ignoreDiscriminator: boolean): Bbox {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		southWest: BboxSouthWestFromJSON(json['southWest']),
		northEast: BboxSouthWestFromJSON(json['northEast'])
	};
}

export function BboxToJSON(value?: Bbox | null): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		southWest: BboxSouthWestToJSON(value.southWest),
		northEast: BboxSouthWestToJSON(value.northEast)
	};
}
