/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface LngLat
 */
export interface LngLat {
	/**
	 *
	 * @type {number}
	 * @memberof LngLat
	 */
	longitude: number;
	/**
	 *
	 * @type {number}
	 * @memberof LngLat
	 */
	latitude: number;
}

/**
 * Check if a given object implements the LngLat interface.
 */
export function instanceOfLngLat(value: object): boolean {
	let isInstance = true;
	isInstance = isInstance && 'longitude' in value;
	isInstance = isInstance && 'latitude' in value;

	return isInstance;
}

export function LngLatFromJSON(json: any): LngLat {
	return LngLatFromJSONTyped(json, false);
}

export function LngLatFromJSONTyped(json: any, ignoreDiscriminator: boolean): LngLat {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		longitude: json['longitude'],
		latitude: json['latitude']
	};
}

export function LngLatToJSON(value?: LngLat | null): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		longitude: value.longitude,
		latitude: value.latitude
	};
}
