/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { exists, mapValues } from '../runtime';
/**
 * Check if a given object implements the LngLat interface.
 */
export function instanceOfLngLat(value) {
	let isInstance = true;
	isInstance = isInstance && 'longitude' in value;
	isInstance = isInstance && 'latitude' in value;
	return isInstance;
}
export function LngLatFromJSON(json) {
	return LngLatFromJSONTyped(json, false);
}
export function LngLatFromJSONTyped(json, ignoreDiscriminator) {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		longitude: json['longitude'],
		latitude: json['latitude']
	};
}
export function LngLatToJSON(value) {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		longitude: value.longitude,
		latitude: value.latitude
	};
}
//# sourceMappingURL=LngLat.js.map
