/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RoutingConfigBbox } from './RoutingConfigBbox';
import {
    RoutingConfigBboxFromJSON,
    RoutingConfigBboxFromJSONTyped,
    RoutingConfigBboxToJSON,
} from './RoutingConfigBbox';

/**
 * 
 * @export
 * @interface RoutingConfig
 */
export interface RoutingConfig {
    /**
     * 
     * @type {number}
     * @memberof RoutingConfig
     */
    graphVersion: number;
    /**
     * 
     * @type {RoutingConfigBbox}
     * @memberof RoutingConfig
     */
    bbox: RoutingConfigBbox;
}

/**
 * Check if a given object implements the RoutingConfig interface.
 */
export function instanceOfRoutingConfig(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "graphVersion" in value;
    isInstance = isInstance && "bbox" in value;

    return isInstance;
}

export function RoutingConfigFromJSON(json: any): RoutingConfig {
    return RoutingConfigFromJSONTyped(json, false);
}

export function RoutingConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoutingConfig {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'graphVersion': json['graphVersion'],
        'bbox': RoutingConfigBboxFromJSON(json['bbox']),
    };
}

export function RoutingConfigToJSON(value?: RoutingConfig | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'graphVersion': value.graphVersion,
        'bbox': RoutingConfigBboxToJSON(value.bbox),
    };
}

