/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { exists, mapValues } from '../runtime';
import {
	BboxSouthWestFromJSON,
	BboxSouthWestFromJSONTyped,
	BboxSouthWestToJSON
} from './BboxSouthWest';
/**
 * Check if a given object implements the RoutingConfigBbox interface.
 */
export function instanceOfRoutingConfigBbox(value) {
	let isInstance = true;
	isInstance = isInstance && 'southWest' in value;
	isInstance = isInstance && 'northEast' in value;
	return isInstance;
}
export function RoutingConfigBboxFromJSON(json) {
	return RoutingConfigBboxFromJSONTyped(json, false);
}
export function RoutingConfigBboxFromJSONTyped(json, ignoreDiscriminator) {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		southWest: BboxSouthWestFromJSON(json['southWest']),
		northEast: BboxSouthWestFromJSON(json['northEast'])
	};
}
export function RoutingConfigBboxToJSON(value) {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		southWest: BboxSouthWestToJSON(value.southWest),
		northEast: BboxSouthWestToJSON(value.northEast)
	};
}
//# sourceMappingURL=RoutingConfigBbox.js.map
