/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { exists, mapValues } from '../runtime';
import { RouteNodeFromJSON, RouteNodeFromJSONTyped, RouteNodeToJSON } from './RouteNode';
/**
 * Check if a given object implements the Route interface.
 */
export function instanceOfRoute(value) {
	let isInstance = true;
	isInstance = isInstance && 'nodes' in value;
	return isInstance;
}
export function RouteFromJSON(json) {
	return RouteFromJSONTyped(json, false);
}
export function RouteFromJSONTyped(json, ignoreDiscriminator) {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		nodes: json['nodes'].map(RouteNodeFromJSON)
	};
}
export function RouteToJSON(value) {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		nodes: value.nodes.map(RouteNodeToJSON)
	};
}
//# sourceMappingURL=Route.js.map
