/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RouteNode } from './RouteNode';
import { RouteNodeFromJSON, RouteNodeFromJSONTyped, RouteNodeToJSON } from './RouteNode';

/**
 *
 * @export
 * @interface RoutingResult
 */
export interface RoutingResult {
	/**
	 *
	 * @type {number}
	 * @memberof RoutingResult
	 */
	totalMeters: number;
	/**
	 *
	 * @type {Array<RouteNode>}
	 * @memberof RoutingResult
	 */
	nodes: Array<RouteNode>;
}

/**
 * Check if a given object implements the RoutingResult interface.
 */
export function instanceOfRoutingResult(value: object): boolean {
	let isInstance = true;
	isInstance = isInstance && 'totalMeters' in value;
	isInstance = isInstance && 'nodes' in value;

	return isInstance;
}

export function RoutingResultFromJSON(json: any): RoutingResult {
	return RoutingResultFromJSONTyped(json, false);
}

export function RoutingResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoutingResult {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		totalMeters: json['totalMeters'],
		nodes: (json['nodes'] as Array<any>).map(RouteNodeFromJSON)
	};
}

export function RoutingResultToJSON(value?: RoutingResult | null): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		totalMeters: value.totalMeters,
		nodes: (value.nodes as Array<any>).map(RouteNodeToJSON)
	};
}
